### ISSUE TITLE
Rom loads incorrectly to memory

### ISSUE THREAD

**Issue by Nyapp** [Nyapp/CHIP-8-Emulator#2]
Each byte of the rom is followed by a null byte. Will fix later

**Comment by TheUltimatum** [comment]
was this causing the failure to run?

**Comment by Nyapp** [comment]
Partially. I fixed it and it still doesn't work, but it can get a lot further without calling an address out of the rom and start trying to execute null instructions. I took some time out of my life to implement some debugging features so identifying the rest of the bugs should be a piece of cake.
